name: "Check coverage report"
description: "Validates code coverage reports"
author: "Seu Nome"
inputs:
  report-file:
    description: "Arquivo XML de cobertura gerado pelo JaCoCo"
    required: true
    default: "target/site/jacoco/jacoco.xml"
  min-coverage:
    description: "Cobertura mínima exigida (%)"
    required: true
    default: "80"
  report-format:
    description: "Formato do relatório de cobertura (auto, jacoco, cobertura, opencover, dotcover, visualstudio, ncover)"
    required: false
    default: "auto"

branding:
  icon: 'activity'
  color: 'orange'

runs:
  using: "node20"
  main: "dist/index.js"
